### ISSUE TITLE
Indexing prior history

### ISSUE THREAD

**Issue by Olshansk** [ddworken/hishtory#24]
Prior to installing `hishtory`, my `zsh` history was stored in `$HISTFILE`. Is there an existing tool to do a one time index of that into `hishtory.db`?

**Comment by ddworken** [comment]
Yes! Just do `cat $HISTFILE | hishtory import` to import it. This generally happens by default, but if you have a non-standard HISTFILE it currently won't work (though I will fix that).

**Comment by ddworken** [comment]
Just checked, and it should have respected `HISTFILE` for zsh, did it not? Though I realized that it didn't respect it for bash which I fixed in 6ded150.

**Comment by ddworken** [comment]
Marking as closed. Please reopen if you're still running into this or have any other issues.

**Comment by Olshansk** [comment]
@ddworken I appreciate the details and added documentation,  but it still doesn't work, even after the manual import. See the following screenshot:

<img width="1608" alt="Screen Shot 2022-11-11 at 1 38 11 PM" src="https://user-images.githubusercontent.com/1892194/201434528-5ea7f01f-e262-4e56-bb65-a835e6419c90.png">

Any suggestions on how to debug?

**Comment by ddworken** [comment]
Can you execute `PRAGMA journal_mode = WAL;` in sqlite and then re-run the `SELECT count(*) FROM history_entries`? I suspect that the history entries were imported, but they just weren't ever checkpointed. If that doesn't show all of them, can you run `hishtory export | wc -l`?

**Comment by Olshansk** [comment]
No luck unfortunately 
<img width="645" alt="Screen Shot 2022-11-12 at 11 23 46 AM" src="https://user-images.githubusercontent.com/1892194/201491167-d8cb64fe-a0e3-4a1f-95f6-a3dccb74cad8.png">

**Comment by ddworken** [comment]
re: importing: Thanks! I'm still looking into this. 

re: ZDOTDIR: Thank you for pointing this out! I filed #29 to track this and will absolutely get this fixed.

**Comment by Olshansk** [comment]
@ddworken Do you have any updates regarding indexing prior history?
