### ISSUE TITLE
Minor issue on shutdown

### ISSUE THREAD

**Issue by richjames0** [ddworken/hishtory#69]
Not a huge deal but creating an issue in case it's helpful - I just returned to a bash session on a remote machine that was pretty old (days or a week) and ctrl-Dd it. I got the following:
`hishtory v0.193 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:73: failed to build history entry: failed to get cwd for last command: stat .: stale NFS file handle`

It seemed also to stop the exit process (eventually I just Xd my iTerm pane). My CWD was on an NFS share so I suspect that part is correct and stale doesn't seem unreasonable in context.

**Comment by ddworken** [comment]
I believe that 0a694c39d5aa3ea17d0aaa9a17c6d27cf8374568 should fix this. Just run `hishtory update` and let me know if you notice this again!

**Comment by kimusan** [comment]
I am still seeing this one with latest:
 hishtory update  
Latest version (v0.268) is already installed
 %  ~/.l/p/v/f/bin  2024/02/05 12:07:40 hishtory v0.268 fatal error at github.com/ddworken/hishtory/client/cmd/saveHistoryEntry.go:190: failed to build history entry: failed to get cwd for last command: no such file or directory



This is ubuntu 23.10 in WSL2 running Fish Shell.

**Comment by kimusan** [comment]
nevermind... just realized that I was in a venv folder and that an update command probably had updated the folder so I suddenly was located in a non-existing folder.
